spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 5
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 10000